kind: pipeline
type: docker
name: Drone CI

platform:
  os: linux
  arch: arm

steps:
  - name: Try it
    image: docker.io/library/alpine:latest
    commands:
      - "apk --update --no-cache upgrade"
      - "apk add --no-cache openssl"
      - "nproc"
      - "cat /proc/cpuinfo"
      - "openssl speed -evp sha256"
