kind: pipeline
type: docker
name: Drone CI

platform:
  os: linux
  arch: amd64

steps:
  - name: Try it
    image: docker.io/library/archlinux:base-devel
    commands:
      - "pacman -Syu --noconfirm openssl"
      - "nproc"
      - "cat /proc/cpuinfo"
      - "openssl speed -evp sha256"
